import type { Metadata } from 'next';
import { Cormorant, Outfit } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav';
import Header from '@/components/Header';

const cormorant = Cormorant({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cormorant',
});

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${cormorant.variable}`}>
      <body>
        <div className="container mx-auto flex h-full flex-col">
          <Header />
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
